// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FataAquana
{
	public partial class AankoopController : NSViewController
	{
		public AankoopController (IntPtr handle) : base (handle)
		{
		}
	}
}
