// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Diagnostics;
using System.Collections.Generic;

namespace FataAquana
{
	public partial class AankoopController : NSViewController
	{
		private PersoonController _parentController;
		private AankoopModel _aankoop;
		internal bool IsNieuw = false;

		public List<AankoopModel> Aankopen { get; set; } = new List<AankoopModel>();

		public AankoopController(IntPtr handle) : base(handle)
		{

		}

		#region Override Methods
		public override void AwakeFromNib()
		{
			Debug.WriteLine("Start: AankoopController.AwakeFromNib");

			//base.AwakeFromNib();

			_parentController = this.PresentingViewController as PersoonController;
			if (_parentController != null)
			{
				Aankoop = _parentController.SelectedAankoop;

				if (Aankoop == null)
				{
					Aankoop = new AankoopModel();
					GekochtOpDate.DateValue = AppDelegate.DateTimeToNSDate(DateTime.Now);
					GekochtOpText.StringValue = String.Empty;
					IsNieuw = true;
				}
				else {
					GekochtOpText.StringValue = GekochtOpDate.DateValue.ToString();
				}
			
				Debug.WriteLine("GekochtOpDate: " + GekochtOpDate.DateValue);
				Debug.WriteLine("GekochtOpText: " + GekochtOpText.StringValue);

				if (ApparatenCombobox != null)
				{
					ApparatenCombobox.UsesDataSource = true;
					ApparatenCombobox.Completes = true;
					ApparatenCombobox.DataSource = new ApparatenComboDS();

					if (!Aankoop.ApparaatNaam.Equals(string.Empty))
					{
						var index = ApparatenCombobox.DataSource.IndexOfItem(ApparatenCombobox, Aankoop.ApparaatNaam);
						ApparatenCombobox.SelectItem(index);
					}
				}
			}
			Debug.WriteLine("Start: AankoopController.AwakeFromNib");
		}

		[Export("Aankoop")]
		public AankoopModel Aankoop
		{
			get { return _aankoop; }
			set
			{
				WillChangeValue("Aankoop");
				_aankoop = value;
				DidChangeValue("Aankoop");
			}
		}
		#endregion

		partial void CancelButton(NSObject sender)
		{
			Debug.WriteLine("Start: AankoopController.CancelButton");

			Debug.WriteLine("GekochtOpDate: " + GekochtOpDate.DateValue);
			Debug.WriteLine("GekochtOpText: " + GekochtOpText.StringValue);

			DismissController(this);

			Debug.WriteLine("Einde: AankoopController.CancelButton");
		}

		partial void SaveButton(NSObject sender)
		{
			Debug.WriteLine("Start: AankoopController.SaveButton");

			if (ApparatenCombobox.DataSource != null)
			{
				ApparatenComboDS comboDS = ApparatenCombobox.DataSource as ApparatenComboDS;

				var selectedAankoop = comboDS.Apparaten[(int)ApparatenCombobox.SelectedIndex];

				Aankoop.PersoonID = _parentController.Persoon.ID;
				Aankoop.ApparaatID = selectedAankoop.ID;

				Debug.WriteLine("GekochtOpDate: " + GekochtOpDate.DateValue);
				Debug.WriteLine("GekochtOpText: " + GekochtOpText.StringValue);

				if (IsNieuw)
				{
					Aankoop.Create(AppDelegate.Conn);
				}
				else 
				{
					Aankoop.Update(AppDelegate.Conn);
				}


				if (_parentController != null)
				{
					_parentController.LoadTables();
				}
			}

			DismissController(this);

			Debug.WriteLine("Einde: AankoopController.SaveButton");
		}
	}
}
