// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Diagnostics;

namespace FataAquana
{
	public partial class PersoonController : NSViewController
	{
		#region private variables
		private PersoonModel _persoon;

		private GevolgdeOpleidingenDS dsGevolgdeOpleidingen = null;
		private AankopenDS dsAankopen = null;
		private OnderhoudDS dsOnderhoud = null;
		private LidmaatschappenDS dsLidmaatschappen = null;
		#endregion

		#region Constructors
		public PersoonController(IntPtr handle) : base (handle)
		{
		}
		#endregion

		internal void LoadTables()
		{
			Debug.WriteLine("Start: PersoonController.LoadTables");

			dsGevolgdeOpleidingen = new GevolgdeOpleidingenDS(AppDelegate.Conn, Persoon);
			if (GevolgdeOpleidingenTable != null)
			{
				// Populate the Product Table
				GevolgdeOpleidingenTable.DataSource = dsGevolgdeOpleidingen;
				GevolgdeOpleidingenTable.Delegate = new GevolgdeOpleidingenDelegate(dsGevolgdeOpleidingen);
			}
		
			dsAankopen = new AankopenDS(AppDelegate.Conn, Persoon);
			if (AankopenTable != null)
			{
				// Populate the Product Table
				AankopenTable.DataSource = dsAankopen;
				AankopenTable.Delegate = new AankopenDelegate(dsAankopen);
			}

			dsOnderhoud = new OnderhoudDS(AppDelegate.Conn, Persoon);
			if (OnderhoudTable != null)
			{
				// Populate the Product Table
				OnderhoudTable.DataSource = dsOnderhoud;
				OnderhoudTable.Delegate = new OnderhoudDelegate(dsOnderhoud);
			}

			dsLidmaatschappen = new LidmaatschappenDS(AppDelegate.Conn, Persoon);
			if (LidmaatschappenTable != null)
			{
				// Populate the Product Table
				LidmaatschappenTable.DataSource = dsLidmaatschappen;
				LidmaatschappenTable.Delegate = new LidmaatschappenDelegate(dsLidmaatschappen);
			}

			Debug.WriteLine("Einde: PersoonController.LoadTables");
		}

		public override void AwakeFromNib()
		{
			Debug.WriteLine("Start: PersoonController.AwakeFromNib");

			base.AwakeFromNib();

			Persoon = AppDelegate.SelectedPersoon;

			LoadTables();

			Debug.WriteLine("Einde: PersoonController.AwakeFromNib");
		}

		[Export("Persoon")]
		public PersoonModel Persoon
		{
			get { return _persoon; }
			set
			{
				WillChangeValue("Persoon");
				_persoon = value;
				DidChangeValue("Persoon");
			}
		}

		partial void CancelButton(NSButton sender)
		{
			Debug.WriteLine("Start: PersoonController.CancelButton");

			DismissController(this);

			Debug.WriteLine("Einde: PersoonController.CancelButton");
		}

		#region Actions
		[Action("WijzigFotoClicked:")]
		public void WijzigFotoClicked(NSObject sender)
		{
			Debug.WriteLine("Start: PersoonController.WijzigFotoClicked");

			var dlg = NSOpenPanel.OpenPanel;
			dlg.CanChooseFiles = true;
			dlg.CanChooseDirectories = false;
			dlg.AllowedFileTypes = new string[] { "jpg", "jpeg", "png", "tiff" };

			if (dlg.RunModal() == 1)
			{
				// Nab the first file
				var url = dlg.Urls[0];

				if (url != null)
				{
					var path = url.Path;
					Persoon.Imagepath = url.Path;
				}
			}
		}

		[Action("GevolgdeOpleidingAddClicked:")]
		public void GevolgdeOpleidingAddClicked(Foundation.NSObject sender)
		{
			Debug.WriteLine("Start: PersoonController.GevolgdeOpleidingAddClicked");

			var newGevolgdeOpleiding = new GevolgdeOpleidingModel();

			PerformSegue("GevolgdeOpleidingSegue", this);

			Debug.WriteLine("Einde: PersoonController.GevolgdeOpleidingAddClicked");
		}

		[Action("GevolgdeOpleidingRemoveClicked:")]
		public void GevolgdeOpleidingRemoveClicked(Foundation.NSObject sender)
		{
			Debug.WriteLine("Start: PersoonController.GevolgdeOpleidingRemoveClicked");

			//var selectedRowIndex = PersonenTable.SelectedRow;
			//var selectedPerson = ds.Personen[(int)selectedRowIndex] as PersoonModel;
			//selectedPerson.Delete(AppDelegate.Conn);
			//ReloadTable();
		}

		#endregion

		#region Events
		public delegate void PersonModifiedDelegate(PersoonModel persoon);
		public event PersonModifiedDelegate PersonModified;

		internal void RaisePersonModified(PersoonModel persoon)
		{
			Debug.WriteLine("Start: PersoonController.RaisePersonModified");

			if (this.PersonModified != null) this.PersonModified(persoon);
		}
		#endregion
	}
}
