// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Diagnostics;

namespace FataAquana
{
	public partial class ClubsController : NSViewController
	{
		public ClubModel SelectedClub = null;
		public ClubsDS ds = null;

		#region Computed Properties

		#endregion

		#region Constructors
		// Called when created from unmanaged code
		public ClubsController(IntPtr handle) : base (handle)
		{
			Initialize();
		}

		// Called when created directly from a XIB file
		[Export("initWithCoder:")]
		public ClubsController(NSCoder coder) : base (coder)
		{
			Initialize();
		}

		// Call to load from the XIB/NIB file
		public ClubsController() : base("subviewClubs", NSBundle.MainBundle)
		{
			Initialize();
		}

		// Shared initialization code
		void Initialize()
		{
		}
		#endregion

		#region Override Methods
		public override void AwakeFromNib()
		{
			base.AwakeFromNib();

			// Create the Occupation Table Data Source and populate it
			ds = new ClubsDS(AppDelegate.Conn);

			if (ClubsTable != null)
			{
				// Populate the Product Table
				ClubsTable.DataSource = ds;
				ClubsTable.Delegate = new ClubsDelegate(ds);
			}
		}
		#endregion

		#region Custom Methods
		partial void ClubAddClicked(NSButton sender)
		{
			Debug.WriteLine("Start: ClubsController.ClubAddClicked");

			SelectedClub = null;

			PerformSegue("ClubSegue", this);

			Debug.WriteLine("Einde: ClubsController.ClubAddClicked");
		}

		partial void ClubRemoveClicked(NSButton sender)
		{
			Debug.WriteLine("Start: ClubsController.ClubRemoveClicked");

			if ((int)ClubsTable.SelectedRow >= 0)
			{
				SelectedClub = ds.Clubs[(int)ClubsTable.SelectedRow] as ClubModel;

				// Configure alert
				var alert = new NSAlert()
				{
					AlertStyle = NSAlertStyle.Informational,
					InformativeText = $"Weet je zeker dat je de club {SelectedClub.ClubNaam} wilt verwijderen?\n\nDit kan niet meer ongedaan gemaakt worden.",
					MessageText = $"Delete {SelectedClub.ClubNaam}?",
				};
				alert.AddButton("Cancel");
				alert.AddButton("Delete");
				alert.BeginSheetForResponse(this.View.Window, (result) =>
				{
					// Should we delete the requested row?
					if (result == 1001)
					{
						// Remove the given row from the dataset
						SelectedClub.Delete(AppDelegate.Conn);
						ds.Clubs.Remove(SelectedClub);
						ReloadTable();
					}
				});
			}

			Debug.WriteLine("Einde: ClubsController.ClubRemoveClicked");
		}

		[Export("RowDoubleClicked:")]
		public void RowDoubleClicked(NSObject sender)
		{
			Debug.WriteLine("Start: ClubsController.RowDoubleClicked");

			SelectedClub = ds.Clubs[(int)ClubsTable.SelectedRow] as ClubModel;

			PerformSegue("ClubSegue", this);

			Debug.WriteLine("Einde: ClubsController.RowDoubleClicked");
		}

		public void ReloadTable()
		{
			ClubsTable.ReloadData();
		}
		#endregion
	}
}
