// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Diagnostics;

namespace FataAquana
{
	public partial class ClubsController : NSViewController
	{
		private ClubsDS ds = null;

		#region Computed Properties
		// Strongly typed view accessor
		//public new ClubsView View
		//{
		//	get
		//	{
		//		return (ClubsView)base.View;
		//	}
		//}
		#endregion

		#region Constructors
		// Called when created from unmanaged code
		public ClubsController(IntPtr handle) : base (handle)
		{
			Initialize();
		}

		// Called when created directly from a XIB file
		[Export("initWithCoder:")]
		public ClubsController(NSCoder coder) : base (coder)
		{
			Initialize();
		}

		// Call to load from the XIB/NIB file
		public ClubsController() : base("subviewClubs", NSBundle.MainBundle)
		{
			Initialize();
		}

		// Shared initialization code
		void Initialize()
		{
		}
		#endregion

		#region Override Methods
		public override void AwakeFromNib()
		{
			base.AwakeFromNib();

			// Create the Occupation Table Data Source and populate it
			//var DataSource = new TableORMDatasource(AppDelegate.Conn);
			ds = new ClubsDS(AppDelegate.Conn);

			if (ClubsTable != null)
			{
				// Populate the Product Table
				ClubsTable.DataSource = ds;
				ClubsTable.Delegate = new ClubsDelegate(ds);
			}
		}
		#endregion

		#region Custom Methods
		partial void ClubAddClicked(NSButton sender)
		{
			//var newClub = new ClubModel();

			//var sheet = new ClubEditorSheetController(newClub, true);
			//// Wire-up
			//sheet.ClubModified += (club) =>
			//{
			//	// Save club to database
			//	club.Create(AppDelegate.Conn);

			//	if (ClubsTable != null)
			//	{
			//		ds.AddClub(club);

			//		ReloadTable();
			//	}
			//};

			//// Display sheet
			//sheet.ShowSheet(NSApplication.SharedApplication.KeyWindow);
		}

		partial void ClubRemoveClicked(NSButton sender)
		{
			// vragen of je zeker ben
			var selectedRowIndex = ClubsTable.SelectedRow;
			SelectedClub = ds.Clubs[(int)selectedRowIndex] as ClubModel;
			ds.Clubs.Remove(SelectedClub);
			SelectedClub.Delete(AppDelegate.Conn);
			ReloadTable();
		}

		public void ReloadTable()
		{
			ClubsTable.ReloadData();
		}

		public ClubModel SelectedClub = new ClubModel();

		[Export("RowDoubleClicked:")]
		public void RowDoubleClicked(NSObject sender)
		{
			//SelectedClub = ds.Clubs[(int)ClubsTable.SelectedRow] as ClubModel;

			//Debug.WriteLine("Clicked: " + SelectedClub.ID + "|" + SelectedClub.ClubNaam);

			////PerformSegue("ClubSeque", this);

			//var sheet = new ClubEditorSheetController(SelectedClub, true);
			//// Wire-up
			//sheet.ClubModified += (club) =>
			//{
			//	// Save club to database
			//	club.Update(AppDelegate.Conn);

			//	if (ClubsTable != null)
			//	{
			//		ReloadTable();
			//	}
			//};

			//// Display sheet
			//sheet.ShowSheet(NSApplication.SharedApplication.KeyWindow);
		}
		#endregion
	}
}
