// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FataAquana
{
	public partial class ClubController : NSViewController
	{
		private ClubModel _club;

		public ClubController (IntPtr handle) : base (handle)
		{
		}

		partial void CancelAction(NSButton sender)
		{
			DismissViewController(this);
		}

		public override void AwakeFromNib()
		{
			base.AwakeFromNib();
		}

		public ClubModel Club
		{
			get { return _club; }
			set
			{
				WillChangeValue("Club");
				_club = value;
				DidChangeValue("Club");
			}
		}

	}
}
