// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FataAquana
{
	public partial class LeftViewController : NSViewController
	{
		#region Private Variables
		private SubviewType ViewType = SubviewType.None;
		#endregion

		#region Constructors
		// Called when created from unmanaged code
		public LeftViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			GroepLijst.Enabled = false;
		}
		#endregion

		#region Private Methods
		private void DisplaySubview(SubviewType type)
		{
			// Is thisview already displayed?
			if (ViewType == type) return;

			// Save values
			ViewType = type;
			RaiseViewTypeChanged(type);
		}
		#endregion

		#region Override Methods
		public override void AwakeFromNib()
		{
			base.AwakeFromNib();

			// Populate Source List
			GroepLijst.Initialize();

			var TableViews = new GroepLijstItem("Fata Aquana");

			TableViews.AddItem("Personen", "user1.png", () =>
			{
				DisplaySubview(SubviewType.Personen);
			});
			GroepLijst.AddItem(TableViews);

			var StamObjecten = new GroepLijstItem("Stam Gegevens");
			StamObjecten.AddItem("Opleidingen", "blackboard.png", () =>
			{
				DisplaySubview(SubviewType.Opleidingen);
			});

			StamObjecten.AddItem("Apparaten", "apparatuur.png", () =>
			{
				DisplaySubview(SubviewType.Apparaten);
			});

			StamObjecten.AddItem("Clubs", "users2.png", () =>
			{
				DisplaySubview(SubviewType.Clubs);
			});
			GroepLijst.AddItem(StamObjecten);

			// Now Display the groeps
			GroepLijst.ReloadData();
			GroepLijst.ExpandItem(null, true);
		}

		#endregion

		public void EnableGroepLijst()
		{
			GroepLijst.Enabled = true;
		}

		#region Events
		public delegate void ViewTypeChangedDelegate(SubviewType viewType);
		public event ViewTypeChangedDelegate ViewTypeChanged;

		internal void RaiseViewTypeChanged(SubviewType type)
		{
			if (AppDelegate.Conn != null)
			{
				if (this.ViewTypeChanged != null)
					this.ViewTypeChanged(type);
			}
		}
		#endregion
	}
}
