// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FataAquana
{
	public partial class MainWindowApp : NSWindow
	{
		public MainWindowApp (IntPtr handle) : base (handle)
		{
		}
	}
}
