// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FataAquana
{
	public partial class RightViewController : NSViewController
	{
		#region Constructors
		public RightViewController(IntPtr handle) : base(handle)
		{
		}
		#endregion

		#region Public Methods
		public void ShowView(SubviewType type)
		{

			// Take action based on requested type
			switch (type)
			{
				case SubviewType.Personen:
					PerformSegue("PersonenSeque", this);
					break;
				case SubviewType.Opleidingen:
					PerformSegue("OpleidingenSeque", this);
					break;
				case SubviewType.Apparaten:
					PerformSegue("ApparatenSeque", this);
					break;
				case SubviewType.Clubs:
					PerformSegue("ClubsSeque", this);
					break;

			}
		}
		#endregion
	}
}
