// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Diagnostics;

namespace FataAquana
{
	public partial class WindowsController : NSWindowController
	{
		public WindowsController (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib()
		{
			base.AwakeFromNib();

			// Wire up the toolbar controls
			OpenDB.Enabled = true;
			OpenDB.Activated += (sender, e) =>
			{
				AppDelegate.Conn = AppDelegate.GetDatabaseConnection();

				OpenDB.Enabled = false;

				Search.Enabled = true;
				Print.Enabled = true;
			};

			Search.Enabled = false;
			Search.Activated += (sender, e) =>
			{
				if (AppDelegate.Conn != null)
				{
					// Als currentview = Personen zoek op Achternaam
					Debug.WriteLine("Zoek: " + Search.ToString());

				}
			};
		}
	}
}
