// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Diagnostics;

namespace FataAquana
{
	public partial class OpleidingController : NSViewController
	{
		private OpleidingenController _parentController;
		private OpleidingModel _opleiding;

		public OpleidingController (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib()
		{
			Debug.WriteLine("Start: OpleidingController.AwakeFromNib");

			base.AwakeFromNib();

			_parentController = this.PresentingViewController as OpleidingenController;

			if (_parentController != null)
			{
				Opleiding = _parentController.SelectedOpleiding;

				if (Opleiding != null)
				{
				}
				else
				{
					Opleiding = new OpleidingModel();
				}
			}

			Debug.WriteLine("Einde: OpleidingController.AwakeFromNib");
		}

		[Export("Opleiding")]
		public OpleidingModel Opleiding
		{
			get { return _opleiding; }
			set
			{
				WillChangeValue("Opleiding");
				_opleiding = value;
				DidChangeValue("Opleiding");
			}
		}

		partial void SaveButton(NSButton sender)
		{
			Debug.WriteLine("Start: OpleidingController.SaveButton");

			if (_parentController.SelectedOpleiding != null)
			{
				Opleiding.Update(AppDelegate.Conn);
			}
			else
			{
				Opleiding.Create(AppDelegate.Conn);
				_parentController.ds.AddOpleiding(Opleiding);
			}

			if (_parentController != null)
			{
				_parentController.ReloadTable();
			}

			DismissController(this);

			Debug.WriteLine("Einde: OpleidingController.SaveButton");
		}

		partial void CancelButton(NSButton sender)
		{
			Debug.WriteLine("Start: OpleidingController.CancelButton");

			DismissController(this);

			Debug.WriteLine("Einde: OpleidingController.CancelButton");
		}

	}
}
