// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Diagnostics;

namespace FataAquana
{
	public partial class OpleidingenController : NSViewController
	{
		public OpleidingModel SelectedOpleiding = null;
		public OpleidingenDS ds = null;

		#region Computed Properties

		#endregion

		#region Constructors
		// Called when created from unmanaged code
		public OpleidingenController(IntPtr handle) : base (handle)
		{
			Initialize();
		}

		// Called when created directly from a XIB file
		[Export("initWithCoder:")]
		public OpleidingenController(NSCoder coder) : base (coder)
		{
			Initialize();
		}

		// Call to load from the XIB/NIB file
		public OpleidingenController() : base("subviewOpleidingen", NSBundle.MainBundle)
		{
			Initialize();
		}

		// Shared initialization code
		void Initialize()
		{
		}
		#endregion


		#region Override Methods
		public override void AwakeFromNib()
		{
			base.AwakeFromNib();

			// Create the Occupation Table Data Source and populate it
			ds = new OpleidingenDS(AppDelegate.Conn);

			if (OpleidingenTable != null)
			{
				// Populate the Product Table
				OpleidingenTable.DataSource = ds;
				OpleidingenTable.Delegate = new OpleidingenDelegate(ds);
			}
		}
		#endregion

		#region Custom Methods
		partial void OpleidingAddClicked(NSButton sender)
		{
			Debug.WriteLine("Start: OpleidingenController.OpleidingAddClicked");

			SelectedOpleiding = null;

			PerformSegue("OpleidingSegue", this);

			Debug.WriteLine("Einde: OpleidingenController.OpleidingAddClicked");
		}
	

		partial void OpleidingRemoveClicked(NSButton sender)
		{
			Debug.WriteLine("Start: OpleidingenController.OpleidingRemoveClicked");

			if ((int)OpleidingenTable.SelectedRow >= 0)
			{
				SelectedOpleiding = ds.Opleidingen[(int)OpleidingenTable.SelectedRow] as OpleidingModel;

				// Configure alert
				var alert = new NSAlert()
				{
					AlertStyle = NSAlertStyle.Informational,
					InformativeText = $"Weet je zeker dat je de opleiding {SelectedOpleiding.OpleidingNaam} wilt verwijderen?\n\nDit kan niet meer ongedaan gemaakt worden.",
					MessageText = $"Delete {SelectedOpleiding.OpleidingNaam}?",
				};
				alert.AddButton("Cancel");
				alert.AddButton("Delete");
				alert.BeginSheetForResponse(this.View.Window, (result) =>
				{
					// Should we delete the requested row?
					if (result == 1001)
					{
						// Remove the given row from the dataset
						SelectedOpleiding.Delete(AppDelegate.Conn);
						ds.Opleidingen.Remove(SelectedOpleiding);
						ReloadTable();
				}
				});
			}
			Debug.WriteLine("Einde: OpleidingenController.OpleidingRemoveClicked");
		}

		[Export("RowDoubleClicked:")]
		public void RowDoubleClicked(NSObject sender)
		{
			Debug.WriteLine("Start: OpleidingenController.RowDoubleClicked");

			SelectedOpleiding = ds.Opleidingen[(int)OpleidingenTable.SelectedRow] as OpleidingModel;

			PerformSegue("OpleidingSegue", this);

			Debug.WriteLine("Einde: OpleidingenController.RowDoubleClicked");
		}

		public void ReloadTable()
		{
			OpleidingenTable.ReloadData();
		}
		#endregion
	}
}
